plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

javafx {
    version = "21"
    modules = ["javafx.controls", "javafx.fxml"]
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Source: https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-core
    implementation("org.hibernate.orm:hibernate-core:7.3.2.Final")
    // Source: https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-hikaricp
    implementation("org.hibernate.orm:hibernate-hikaricp:7.3.2.Final")
    // Source: https://mvnrepository.com/artifact/org.postgresql/postgresql
    implementation("org.postgresql:postgresql:42.7.11")

    // Source: https://mvnrepository.com/artifact/org.mindrot/jbcrypt
    implementation("org.mindrot:jbcrypt:0.4")
}

test {
    useJUnitPlatform()
}

application {
    mainClass = "org.example.Main"
}

run {
    systemProperties System.getProperties()
}